dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: CNlwxio8T4VEd/aeLgCVuS6VTvwxzxpirXl7lImk0C5PpriN8QMGNGGJ7K/IMpnnTYFUn4kE5ff18OiK39zob4VK5qFV7scl8hHSzKk7TLmmoKm42h6PkMm1Qm+Ipm7jGPJNHzMsIz1GpMr9HY4LdR4JJy0ge1EYczdJMh59quV5YYUYQMFESmj5BmZ7HEA79NawoFyHiTDMrANxl4Km/YoLEhyOGbVH2qBOwKxwQBobw4iACqkNh9eCJhAnAnuWFRxh5MPsRjpsIhrZC1weMKAonp2WzUNwfXcoy1yY5mO4tjPCDGgrWVbqHZGXBXOcZmpeACRfN6fPPrbke3lKMXOvFkDi8pls+fqU7rGDrMBWH+x6mN4lVjaA0FdBKx1jY6m5Zsd3r0zqqaB8rG6H02PXDc+rdJW5GMNtpiNlGErH/oufU2oGCqt6sdXPbxy/dBAzNx5Z5UXhBIkX1qFacqv2oafklQrZE7xY96pz+4lEKcwfV2rMDKPjLaFSSNT6234rwmAim12FxrmXdPSwMWqeI/5P+VR+SsbFxGeVsilpAeAvx+IeIyLXP2czqTWznOKaFYV0FkuV/mi1eKHnUJAjgnXbo4s6gGmRf385K4PqjLzKN7rKvSSsJHzNmssxGqT0RcqqS7lKT0ypbReTSHyEPhQ+ZEVbmTsBk3KDnkI=
