cd ---
    - hosts: all
      become: true
      gather_facts: no

      tasks:
      - name: Install required system packages
        apt: name={{ item }} state=latest update_cache=yes
        loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python-pip', 'virtualenv', 'python-setuptools']


      - name: pip_inst
        apt:
          name: python3-pip
          state: present
          force_apt_get: yes
          update_cache: yes

      - name: pip_upg
        pip:
          name: pip
          state: latest

      - name: Install Docker Module for Python
        pip:
            name: docker


      - name: add docker repo
        apt_repository:
            repo="deb https://download.docker.com/linux/ubuntu xenial stable"
            state=present
      - name: install repo gpg key
        apt_key:
            url="https://download.docker.com/linux/ubuntu/gpg"
            state=present
      - name: refresh cache and install docker-ce
        apt:
            name=docker-ce
            update_cache=yes
            state=latest
