{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "95 перцентиль попадания",
   "type": "graph",
   "description": "95 перцентиль попадания",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "График запросов к сервису  UI   с ошибками",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "description": "Количество обращений  к сервису UI",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count [1m])" }
   ]
  }
 ]
}